Version 0.5.0 release.

diff --git a/mkdistrib b/mkdistrib
--- a/mkdistrib
+++ b/mkdistrib
@@ -3,15 +3,39 @@
 # Script to prepare source code and binary distribution files of rEFInd.
 # By Rod Smith, 3/11/2012
 # Updated 11/8/2012 to do more things automatically
+# Updated 12/6/2012 to sign binaries with the rEFInd MOK
 #
 # Usage: ./mkdistrib version
 # where "version" is a version number
 # MUST be run from an x86-64 system, on which the TianoCore build
 # includes both X64 and IA32 build support ("TARGET_ARCH = IA32 X64"
-# in Conf/target.txt).
+# in Conf/target.txt). The MOK files must be available from a disk
+# partition to be mounted via /etc/fstab at /mnt/refind.
 
 
 StartDir=`pwd`
+SBSign=`which sbsign 2> /dev/null`
+KeysDir=/mnt/refind
+
+KeysInfo=`df $KeysDir 2> /dev/null | grep $KeysDir`
+
+if [[ ! -n $SBSign ]] ; then
+   echo "Can't find sbsign binary! Aborting!"
+   exit 1
+fi
+
+if [[ ! -n $KeysInfo ]] ; then
+   mount /mnt/refind
+fi
+
+if [[ $? -ne 0 ]] ; then
+   echo "Error mounting $KeysDir! Aborting!"
+   echo ""
+   exit 1
+fi
+
+# From here on, if there's an error, abort immediately.
+set -e
 
 make clean
 
@@ -19,6 +43,7 @@ make clean
 mkdir -p ../snapshots/$1/refind-$1/icons
 cp --preserve=timestamps icons/*icns ../snapshots/$1/refind-$1/icons/
 cp -a docs images include EfiLib libeg refind filesystems install.sh CREDITS.txt NEWS.txt BUILDING.txt COPYING.txt LICENSE.txt README.txt refind.inf Make.tiano Make.common Makefile refind.conf-sample ../snapshots/$1/refind-$1
+cp $KeysDir/refind.cer $KeysDir/refind.crt ../snapshots/$1/refind-$1/
 
 # Go there and prepare a souce code zip file....
 cd ../snapshots/$1/
@@ -38,17 +63,22 @@ cp refind/refind_ia32.efi $StartDir/
 make clean
 make
 make fs
-mkdir -p refind-bin-$1/refind/drivers_x64
+mkdir -p refind-bin-$1/refind/drivers
 cp -a icons refind-bin-$1/refind/
-cp --preserve=timestamps drivers/*_x64.efi refind-bin-$1/refind/drivers_x64/
+for File in `ls drivers/*_x64.efi` ; do
+   $SBSign --key $KeysDir/refind.key --cert $KeysDir/refind.crt --output refind-bin-$1/refind/$File $File
+done
+mv refind-bin-$1/refind/drivers refind-bin-$1/refind/drivers_x64
 cp --preserve=timestamps filesystems/LICENSE*txt refind-bin-$1/refind/drivers_x64/
 cp --preserve=timestamps refind.conf-sample refind-bin-$1/refind/
-cp refind/refind_x64.efi refind-bin-$1/refind/refind_x64.efi
-cp refind/refind_x64.efi $StartDir
+$SBSign --key $KeysDir/refind.key --cert $KeysDir/refind.crt --output refind-bin-$1/refind/refind_x64.efi refind/refind_x64.efi
+cp refind-bin-$1/refind/refind_x64.efi $StartDir
 cp -a COPYING.txt LICENSE.txt README.txt docs CREDITS.txt install.sh refind-bin-$1
 
 # Prepare the final .zip file and clean up
+cp $KeysDir/refind.cer $KeysDir/refind.crt refind-bin-$1/
 zip -9r ../refind-bin-$1.zip refind-bin-$1
 cd ..
 rm -r refind-$1
 cd $StartDir
+umount $KeysDir
